# Generated by Django 5.0.4 on 2024-05-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
